### ISSUE TITLE
小问题： Mac下看不到文件

### ISSUE THREAD

**Issue by Art-Man** [zijiren233/go-webdav#1]
项目非常棒，有个小问题，就是在MAC下好像看不到对应的文件，测试了下文件上传和目录创建都是成功的；

**Comment by Art-Man** [comment]
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/11453650/229963754-10e5ffe8-c29c-4cd4-b8ef-caeae6184ca7.png">

**Comment by zijiren233** [comment]
windows系统自带的webdav不支持http，必须要https
可能mac也是这样，你可以使用第三方客户端来强制使用http协议

**Comment by 931122** [comment]
我提了一个pr你试试可以吗
